safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
title : IIDN
timezone: UTC
production_url : http://dev.inventit.io
description: ""
disqus_shortname: iidn
analytics: UA-32804324-3
encoding: UTF-8
author :
  name : Inventit Inc.
  github : inventit
  googleplus : 103577935124656848081
  facebookpage : InventitIotDeveloperNetwork
  linkedin : inventit-inc./inventit-iot-developer-network-1365558/product

