safe: true
lsi: false
markdown: rdiscount
pygments: true
rdiscount:
  extensions: [smart]
title : IIDN
production_url : http://dev.yourinventit.com
description: ""
disqus_shortname: iidn
analytics: UA-32804324-3
author :
  name : Inventit Inc.
  github : inventit
  googleplus : 103577935124656848081
  facebookpage : InventitIotDeveloperNetwork
  linkedin : inventit-inc./inventit-iot-developer-network-1365558/product

