safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
title : IIDN
timezone: UTC

production_url : http://dev.inventit.io
i18n : false

#production_url : http://localhost:4000
#i18n : true

description: ""
disqus_shortname: iidn
analytics: UA-32804324-3
analytics_domain: inventit.io
encoding: UTF-8
author :
  name : Inventit Inc.
  github : inventit
  googleplus : 103577935124656848081
  facebookpage : InventitIotDeveloperNetwork

